#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-xfun
Version  : 0.4
Release  : 3
URL      : https://cran.r-project.org/src/contrib/xfun_0.4.tar.gz
Source0  : https://cran.r-project.org/src/contrib/xfun_0.4.tar.gz
Summary  : Miscellaneous Functions by 'Yihui Xie'
Group    : Development/Tools
License  : MIT
BuildRequires : buildreq-R

%description
# xfun
[![Build Status](https://travis-ci.org/yihui/xfun.svg)](https://travis-ci.org/yihui/xfun)
[![Coverage status](https://codecov.io/gh/yihui/xfun/branch/master/graph/badge.svg)](https://codecov.io/github/yihui/xfun?branch=master)
[![Downloads from the RStudio CRAN mirror](https://cranlogs.r-pkg.org/badges/grand-total/xfun)](https://cran.r-project.org/package=xfun)

%prep
%setup -q -c -n xfun

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1540495259

%install
export SOURCE_DATE_EPOCH=1540495259
rm -rf %{buildroot}
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library xfun
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library xfun
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library xfun
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library xfun|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/xfun/DESCRIPTION
/usr/lib64/R/library/xfun/INDEX
/usr/lib64/R/library/xfun/LICENSE
/usr/lib64/R/library/xfun/Meta/Rd.rds
/usr/lib64/R/library/xfun/Meta/features.rds
/usr/lib64/R/library/xfun/Meta/hsearch.rds
/usr/lib64/R/library/xfun/Meta/links.rds
/usr/lib64/R/library/xfun/Meta/nsInfo.rds
/usr/lib64/R/library/xfun/Meta/package.rds
/usr/lib64/R/library/xfun/Meta/vignette.rds
/usr/lib64/R/library/xfun/NAMESPACE
/usr/lib64/R/library/xfun/NEWS.md
/usr/lib64/R/library/xfun/R/xfun
/usr/lib64/R/library/xfun/R/xfun.rdb
/usr/lib64/R/library/xfun/R/xfun.rdx
/usr/lib64/R/library/xfun/doc/index.html
/usr/lib64/R/library/xfun/doc/xfun.R
/usr/lib64/R/library/xfun/doc/xfun.Rmd
/usr/lib64/R/library/xfun/doc/xfun.html
/usr/lib64/R/library/xfun/help/AnIndex
/usr/lib64/R/library/xfun/help/aliases.rds
/usr/lib64/R/library/xfun/help/paths.rds
/usr/lib64/R/library/xfun/help/xfun.rdb
/usr/lib64/R/library/xfun/help/xfun.rdx
/usr/lib64/R/library/xfun/html/00Index.html
/usr/lib64/R/library/xfun/html/R.css
